# Generated by Django 2.2.5 on 2019-09-21 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to=users.models.get_profile_filename)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('state', models.CharField(choices=[('ABI', 'Abia'), ('ADA', 'Adamawa'), ('AKW', 'Akwa-Ibom'), ('ANA', 'Anambra'), ('BAU', 'Bauchi'), ('Bayelsa State', 'Bayelsa'), ('Benue State', 'Benue'), ('Borno State', 'Borno'), ('Cross River State', 'Cross'), ('Delta State', 'Delta'), ('Ebonyi State', 'Ebonyi'), ('Enugu State', 'Enugu'), ('Edo State', 'Edo'), ('FCT - Abuja', 'FCT - Abuja'), ('Gombe State', 'Gombe'), ('Imo State', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna State', 'Kaduna'), ('Kano State', 'Kano'), ('Katsina State', 'Katsina'), ('Kebbi State', 'Kebbi'), ('Kogi State', 'Kogi'), ('Kwara State', 'Kwara'), ('Lagos State', 'Lagos'), ('Nasarawa State', 'Nasarawa'), ('Niger State', 'Niger'), ('Ogun State', 'Ogun'), ('Ondo State', 'Ondo'), ('Osun', 'Osun'), ('Oyo State', 'Oyo'), ('Plateau State', 'Plateau'), ('Rivers State', 'Rivers'), ('Sokoto State', 'Sokoto'), ('Taraba State', 'Taraba'), ('Yobe State', 'Yobe'), ('Zamfara State', 'Zamfara')], default='ABI', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
