# Generated by Django 2.2.5 on 2019-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
