# Generated by Django 2.2.5 on 2019-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190918_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
