# Generated by Django 2.2.5 on 2019-09-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190918_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='author',
        ),
    ]
