# Generated by Django 2.2.5 on 2019-09-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190920_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
