# Generated by Django 2.2.5 on 2019-09-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190920_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
