# Generated by Django 2.2.5 on 2019-10-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20190925_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_add', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Featured Event',
                'verbose_name_plural': 'Featured Events',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='feat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FeaturedEvent'),
        ),
    ]
